name: Check URLs on posts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: urls-checker
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: _posts
        file_types: .md,.html,.markdown
        force_pass: true